"""add stock tables

Revision ID: 0ca32dcce540
Revises: 69b6a843da12
Create Date: 2026-03-10 15:35:11.307579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0ca32dcce540'
down_revision: Union[str, Sequence[str], None] = '69b6a843da12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.Column('list_date', sa.Date(), nullable=True),
    sa.Column('is_st', sa.Boolean(), nullable=False),
    sa.Column('is_delisting', sa.Boolean(), nullable=False),
    sa.Column('total_shares', sa.BigInteger(), nullable=True),
    sa.Column('float_shares', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('stock_daily_quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('high', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('low', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('close', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('turnover_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('pct_change', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'trade_date')
    )
    op.create_index('idx_daily_quotes_date', 'stock_daily_quotes', ['trade_date'], unique=False)
    op.create_index('idx_daily_quotes_stock_date', 'stock_daily_quotes', ['stock_id', 'trade_date'], unique=False, postgresql_ops={'trade_date': 'DESC'})
    op.create_table('stock_fundamentals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('pe_ttm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pb', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ps_ttm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('roe', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('gross_margin', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('net_margin', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('revenue_yoy', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('profit_yoy', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('operating_cf', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('debt_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('float_market_cap', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'report_date')
    )
    op.create_table('stock_technical_indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('ma5', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ma10', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ma20', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ma60', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('macd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('macd_signal', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('macd_hist', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rsi_14', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('boll_upper', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('boll_mid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('boll_lower', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('atr_14', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('volume_ma5', sa.BigInteger(), nullable=True),
    sa.Column('volume_ma20', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'trade_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_technical_indicators')
    op.drop_table('stock_fundamentals')
    op.drop_index('idx_daily_quotes_stock_date', table_name='stock_daily_quotes', postgresql_ops={'trade_date': 'DESC'})
    op.drop_index('idx_daily_quotes_date', table_name='stock_daily_quotes')
    op.drop_table('stock_daily_quotes')
    op.drop_table('stocks')
    # ### end Alembic commands ###
