"""add watchlist tables

Revision ID: 67a63c189a64
Revises: 9b440fad0622
Create Date: 2026-03-10 16:34:02.622516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67a63c189a64'
down_revision: Union[str, Sequence[str], None] = '9b440fad0622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('added_date', sa.Date(), nullable=False),
    sa.Column('quant_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('factor_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('catalyst_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('catalyst_date', sa.Date(), nullable=True),
    sa.Column('recommended_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_recommended', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=10), server_default='active', nullable=False),
    sa.Column('removed_date', sa.Date(), nullable=True),
    sa.Column('removed_reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'added_date')
    )
    op.create_index('idx_watchlist_status', 'watchlist', ['status'], unique=False)
    op.create_table('watchlist_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('quant_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('rank_in_list', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date', 'stock_id')
    )
    op.create_index('idx_watchlist_snapshots_date', 'watchlist_snapshots', ['snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_watchlist_snapshots_date', table_name='watchlist_snapshots')
    op.drop_table('watchlist_snapshots')
    op.drop_index('idx_watchlist_status', table_name='watchlist')
    op.drop_table('watchlist')
    # ### end Alembic commands ###
