"""add geo_events and raw_geo_articles tables

Revision ID: 8545a5d7431b
Revises: 171b880cca46
Create Date: 2026-04-22 17:41:12.763205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8545a5d7431b'
down_revision: Union[str, Sequence[str], None] = '171b880cca46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('impact_level', sa.Integer(), nullable=False),
    sa.Column('categories', sa.String(length=500), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_index('idx_geo_events_active_level_date', 'geo_events', ['is_active', 'impact_level', 'event_date'], unique=False, postgresql_ops={'impact_level': 'DESC', 'event_date': 'DESC'})
    op.create_table('raw_geo_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline', sa.String(length=20), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_processed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline', 'url', name='raw_geo_articles_pipeline_url_key')
    )
    op.create_index('idx_raw_geo_processed', 'raw_geo_articles', ['is_processed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_events_stock_date', table_name='stock_events', postgresql_ops={'event_date': 'DESC'})
    op.create_index(op.f('idx_events_stock_date'), 'stock_events', ['stock_id', sa.literal_column('event_date DESC')], unique=False)
    op.drop_index('idx_raw_geo_processed', table_name='raw_geo_articles')
    op.drop_table('raw_geo_articles')
    op.drop_index('idx_geo_events_active_level_date', table_name='geo_events', postgresql_ops={'impact_level': 'DESC', 'event_date': 'DESC'})
    op.drop_table('geo_events')
    # ### end Alembic commands ###
    op.drop_table('raw_geo_articles')
    op.drop_index('idx_geo_events_active_level_date', table_name='geo_events', postgresql_ops={'impact_level': 'DESC', 'event_date': 'DESC'})
    op.drop_table('geo_events')
    # ### end Alembic commands ###
